server:
  error:
    include-message: always
  servlet:
    context-path: /music
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/music
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:    multipart:      max-file-size: 20000KB
      max-request-size: 20000KB        
logging:
  level:
    root: INFO
#    '[formation.sopra.formationSpringBoot.restcontroller.ClientRestController]': INFO    
  file:
    name: logs.log
    path: /log